from importlib import import_module

__all__ = [
    'BaseSparsifier',
    'MSTSparsifier',
    'MaxSTSparsifier',
    'FastMaxSTSparsifier',
    'EffectiveResistanceSparsifier',
    'LasVegasSpannerSparsifier',
    'RandomSpanningTreeSparsifier',
    'GreedySpanner',
    'HalperinSpanner',
    'KRandomNeighbor',
    'RandomDropout',
    'ERSparsifier',
    'SupportGraphSparsifier',
    'SupportGraphDilationSparsifier',
    'GreedyLowStretchTreeSparsifier',
    'ScalableLowStretchTreeSparsifier',
    'RandomShortestPathTreeSparsifier',
    'JointDilationCongestionSparsifier',
    'ClusteredLazyJointDilationCongestionSparsifier',
    'ParallelClusteredJointDilationCongestionSparsifier',
    'ScaffoldFastSparsifier',
    'ScaffoldBatchSparsifier',
    'ScaffoldGreedySparsifier',
    'ScaffoldHeapSparsifier',
    'ScaffoldSampleSparsifier',
    'FullGraph',
    'SupportGraphCppSparsifier',
    'LocalDegreeSparsifier',
    'RankDegreeSparsifier',
    'GSPAR',
    'LSPAR',
    'LSIM',
    'ForestFireSparsifier',
    'SCANSparsifier',
    'CutSparsifier',
    'nx_to_pyg',
    'pyg_to_nx',
    'get_sparsifier',
]

_EXPORTS = {
    'BaseSparsifier': ('scaffold_gnn.sparsifiers.base', 'BaseSparsifier'),
    'MSTSparsifier': ('scaffold_gnn.sparsifiers.mst', 'MSTSparsifier'),
    'MaxSTSparsifier': ('scaffold_gnn.sparsifiers.max_spanning_tree', 'MaxSTSparsifier'),
    'FastMaxSTSparsifier': ('scaffold_gnn.sparsifiers.fast_maxst', 'FastMaxSTSparsifier'),
    'EffectiveResistanceSparsifier': ('scaffold_gnn.sparsifiers.effective_resistance', 'EffectiveResistanceSparsifier'),
    'EffectiveResistanceExactSparsifier': ('scaffold_gnn.sparsifiers.effective_resistance', 'EffectiveResistanceExactSparsifier'),
    'LasVegasSpannerSparsifier': ('scaffold_gnn.sparsifiers.las_vegas_spanner', 'LasVegasSpannerSparsifier'),
    'RandomSpanningTreeSparsifier': ('scaffold_gnn.sparsifiers.random_spanning_tree', 'RandomSpanningTreeSparsifier'),
    'GreedySpanner': ('scaffold_gnn.sparsifiers.spanner_greedy', 'GreedySpanner'),
    'HalperinSpanner': ('scaffold_gnn.sparsifiers.spanner_halperin', 'HalperinSpanner'),
    'KRandomNeighbor': ('scaffold_gnn.sparsifiers.k_rand_neighbors', 'KRandomNeighbor'),
    'RandomDropout': ('scaffold_gnn.sparsifiers.random_dropout', 'RandomDropout'),
    'ERSparsifier': ('scaffold_gnn.sparsifiers.er', 'ERSparsifier'),
    'SupportGraphSparsifier': ('scaffold_gnn.sparsifiers.support_graph', 'SupportGraphSparsifier'),
    'SupportGraphDilationSparsifier': ('scaffold_gnn.sparsifiers.support_graph_dilation', 'SupportGraphDilationSparsifier'),
    'GreedyLowStretchTreeSparsifier': ('scaffold_gnn.sparsifiers.low_stretch_tree', 'GreedyLowStretchTreeSparsifier'),
    'ScalableLowStretchTreeSparsifier': ('scaffold_gnn.sparsifiers.scalable_low_stretch_tree', 'ScalableLowStretchTreeSparsifier'),
    'RandomShortestPathTreeSparsifier': ('scaffold_gnn.sparsifiers.random_shortest_path_tree', 'RandomShortestPathTreeSparsifier'),
    'JointDilationCongestionSparsifier': ('scaffold_gnn.sparsifiers.joint_dilation_congestion', 'JointDilationCongestionSparsifier'),
    'ClusteredLazyJointDilationCongestionSparsifier': ('scaffold_gnn.sparsifiers.clustered_joint_dilation_congestion', 'ClusteredLazyJointDilationCongestionSparsifier'),
    'ParallelClusteredJointDilationCongestionSparsifier': ('scaffold_gnn.sparsifiers.scaffold', 'ParallelClusteredJointDilationCongestionSparsifier'),
    'ScaffoldFastSparsifier': ('scaffold_gnn.sparsifiers.scaffold.scaffold_fast', 'ScaffoldFastSparsifier'),
    'ScaffoldBatchSparsifier': ('scaffold_gnn.sparsifiers.scaffold.scaffold_batch', 'ScaffoldBatchSparsifier'),
    'ScaffoldGreedySparsifier': ('scaffold_gnn.sparsifiers.scaffold.scaffold_greedy', 'ScaffoldGreedySparsifier'),
    'ScaffoldHeapSparsifier': ('scaffold_gnn.sparsifiers.scaffold.scaffold_heap', 'ScaffoldHeapSparsifier'),
    'ScaffoldSampleSparsifier': ('scaffold_gnn.sparsifiers.scaffold.scaffold_sample', 'ScaffoldSampleSparsifier'),
    'FullGraph': ('scaffold_gnn.sparsifiers.full_graph', 'FullGraph'),
    'SupportGraphCppSparsifier': ('scaffold_gnn.sparsifiers.support_graph_cpp', 'SupportGraphCppSparsifier'),
    'LocalDegreeSparsifier': ('scaffold_gnn.sparsifiers.local_degree', 'LocalDegreeSparsifier'),
    'RankDegreeSparsifier': ('scaffold_gnn.sparsifiers.rank_degree', 'RankDegreeSparsifier'),
    'GSPAR': ('scaffold_gnn.sparsifiers.g_spar', 'GSPAR'),
    'LSPAR': ('scaffold_gnn.sparsifiers.l_spar', 'LSPAR'),
    'LSIM': ('scaffold_gnn.sparsifiers.l_sim', 'LSIM'),
    'ForestFireSparsifier': ('scaffold_gnn.sparsifiers.forest_fire', 'ForestFireSparsifier'),
    'SCANSparsifier': ('scaffold_gnn.sparsifiers.scan', 'SCANSparsifier'),
    'CutSparsifier': ('scaffold_gnn.sparsifiers.cut_sparsifier', 'CutSparsifier'),
    'nx_to_pyg': ('scaffold_gnn.utils.graph_conversion', 'nx_to_pyg'),
    'pyg_to_nx': ('scaffold_gnn.utils.graph_conversion', 'pyg_to_nx'),
    'get_sparsifier': ('scaffold_gnn.utils.factory', 'get_sparsifier'),
}


def __getattr__(name):
    if name not in _EXPORTS:
        raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
    module_name, attr_name = _EXPORTS[name]
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
