kind: scaffold
sparsifier: scaffold_greedy
parameters:
  joint_init_support: fast-randsf
  joint_alpha: 1.0
  joint_beta: 1.0
  joint_node_beta: 0.0
description: Scaffold-Greedy support construction.
